- name: variables form inventory file
  hosts: local 
  connection: local
  tasks:
    - name: print course details from inventory file
      ansible.builtin.debug:
        msg: "Course name is: {{ COURSE }}, Duration is: {{ DURATION }}, Trainer is: {{ TRAINER }}"